spring.application.name=alert-management-service
server.port=${PORT:8087}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/terraalert}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/terraalert}