spring.application.name=data-ingestion-service
server.port=${PORT:8082}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/terraalert}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/terraalert}

weather.api.base-url=https://api.open-meteo.com/v1/forecast
weather.ingestion.interval=3600000

data-processing.service.url=${DATA_PROCESSING_SERVICE_URL:http://localhost:8083}